imu_filter:
  ros__parameters:
    # Core settings
    stateless: false                    # Use previous state for better filtering
    use_mag: true                 # Disable magnetometer for racing (magnetic interference)
    publish_tf: false                   # Publish TF for visualization/debugging
    reverse_tf: false                   # Standard TF direction
    
    # Frame settings
    fixed_frame: "imu_top"                 # Reference frame
    world_frame: "enu"                  # East-North-Up world frame
    
    # Timing
    constant_dt: 0.01                   # 100Hz if your IMU runs at 100Hz, 0.005 for 200Hz
    
    # Filter parameters
    gain: 0.0063482977748                    
    zeta: 0.00733038285838                 
    
    # Magnetometer bias (not used if use_mag: false)
    mag_bias_x: -1.0
    mag_bias_y: 1.6
    mag_bias_z: 0.0


    
    # Output settings
    orientation_stddev: 0.05            # Realistic uncertainty estimate
    publish_debug_topics: true          # Useful for tuning
